apiVersion: v1
data:
    access-token: ENC[AES256_GCM,data:EAQHqPbCcKieLwrHA3LlE/BlJtUXCnh5AUfOth0nxPxTHZFTEjXtYg==,iv:B9uUcwb3MEcMW9tQam9Va6MBJ39aOfsT33HTZxKRw4Y=,tag:X0KxSKqSUX9XqQIOMmXKjA==,type:str]
kind: Secret
metadata:
    name: dataset-register-qlever
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dm5sdVJDQU5vaVFGNUpx
            SVlJM3R3SXczaTFlSkl5MW1mVEdkS1ZRL21BCi9VdmduWW9BVmxxeTJRMzZsb1du
            NkwwRWNaVG5XS0RKdWhtbFJQeHdJWEkKLS0tIGJLU0RaYzdnT01jMElib3F4REdQ
            SjJEL1ZIYnJXc01PKy9IUEw2d0xXRjQKiterHRwsB2aE5TtzgQc0XZtMBvDTxDOS
            ktz527K1XKMNTlzwktMIUxWc5vGkLewAkb7rbF/jCih6+M2GnK6Pmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T19:54:12Z"
    mac: ENC[AES256_GCM,data:IqyOOwZGJFxU8GtgT78vUd/6Dbv9K9YkE4LuT5DHUrv5WLIDQdsssXo1HL449QMy9xjLQHn+dzuw4y7rCds1Ij631bxSUEHVjSmEe2kcDwPTvC6XO90iJYBiTZUIykJALB08v5jcqFQbZfCT0KSbZWsWOpV/atJ1QcVGNPVsvhc=,iv:PjovgBYwPbLMvQz9sNvkzj/BXXnv4E4/JGBKTME9yBY=,tag:kYXlXDxCSTT5rGKjLwTpAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
