apiVersion: v1
kind: Secret
metadata:
    name: dataset-register-api-token
    namespace: nde
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:9EySLTekHeGtZS/99VpsIORmi6hwgh1uMq0l9UfM,iv:F/FJ99+Iva9vITq2cHSuKp56ByPJl36j2U8LHJvMRzE=,tag:LEbqSNUpC0KcYlaHomBe8A==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtam9PRW1jQUh1Sm5Sb01O
            eWQ0aXNuVGdJS3VaT3QwODNqd1lQMXpmaUJnCkRqcWJqM1R2dTZST1BCbkxKcDQ2
            WWxaM1pjbEdldWVBbWFQdmJ4aUdwb0kKLS0tIC9XQ0xWZWo1WXNwYzFYaHlwYXcz
            eDJjamdLSGM4UnZYWEZYZUlvbTFua00KXUb4h3oeiA2C8cWAbTj1i3DROQaNdExZ
            fclMQVHfrSPZqUPr8hjw4pK6PmV4PDSoIFwb+MLrFBSBgc8+77Hsmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T19:50:30Z"
    mac: ENC[AES256_GCM,data:gn4dqaxeTbBdrXzcp6xs5uHS5wzMTa4bZO8aMi51V0mLCfuF8N/LBcbjkrF8ys68p9I0lTmrj4CIoxuftNzlmWVmwZK3bjVVGZXY7yQQOBeRTAdYMLjcBmZPgx7V7qPywGEMq8nydduKAen0mMSYN3LNHME0DMKmoixGjodKqKw=,iv:unek3RW10FLrXwT5GZ89FaapF8m31yEPguJnqcDpbvY=,tag:lQKdA1MaGaI5zmkuMaDfHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
