apiVersion: v1
kind: Secret
metadata:
    name: dataset-register-s3
    namespace: nde
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:CzeBhlHGDPopRoBHzYakONIdHZM=,iv:wN0Sav06wEkk180gyqZK/ld3ESzrYwHv/jXLqUA0bHg=,tag:Y7lv4qkMAboCiiOYmxoTUQ==,type:str]
    secret: ENC[AES256_GCM,data:/Hz4JwTRghQRAwjj8/W3cfOpt67KEWvJyPQWS8bSoG3zP3qq6u/NgTok2g==,iv:HL7aMSgzhCnrWYD5zVJKM1hIJ+V6bk7RKOq3gnHzZZg=,tag:dTjkDT51mpA2Nu3OZwUTRw==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSFlKRmxBZ0J1T0hQaDlZ
            bExxc1FSbmROckRhZGI5UDk2cmVvbDNvRGswClhCTWhHaGFRclFRK1RvbnBqelZS
            UlRPWmR6bUF0U3pIbm5OZzRLT2poMEkKLS0tIEMvNkpLUnNuNGlNNnBOaENhSGQz
            cmhaZGVldDNBd0YvK21McEtWSG1PbVUKksVFWBJBJ/NF7GMzksIU7e4CQ5Twicod
            Fg+Lws0VwQEbUsY9KkLZKi2HlRw41XjzjLYlmcOUI4s5NvRZzzsAQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T10:49:05Z"
    mac: ENC[AES256_GCM,data:LVEbZuTq+UyiNNBQyS/f3/HBSwxS8KkHB1T8HXtoD1p2yOrCtQGedZv2IVLTErVyg0OtO6J2ZHonHRvQmEocORj1SlJu9cKWfquIQn1vlmAgPEodPe+qKrOxROsrC4ABRjY3DbF6gODn9HDgMT8oT7yjCob+MzJp4iprFLD71qc=,iv:jPKBtO1YDRtnnjMZAhi1lkUKCN42LebPTUikoqVYQRk=,tag:wUL8SjLtab+HPSp5vgSO9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
