apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:It2Jl8kqZDO0RihIUGJS1ID3JLr3nUS+XKuGCFxEb32LSkI6NFq5FBWABTrJLY4RcIbJ5FGH32Ye8Kh7UkVlSYq5Y5NQD91sD3hkmGEfIG8Xr7bSp0L6etNqnDa25QDCTc+WlC8wrje94vPZhSRvDHMpMFzuLBdTEtcFQOSTVc5CUVwC5hd8ZbL1WqPXQkMt8sDjQMolOqETJaf3q1oIzbVH+yXp39g897LSkmTu/3eUZw1B8eAcFOOi9NrAhMNE9Z3+6wXLD7H6wt6shk7ik1gLmXM7g+FZLzLeJGuaONGQL8mr2tVV6w==,iv:Kp9GTBcworkK73Y703HM/PFs2R71ATvLKpcq0MQXifw=,tag:lggxGYbRzRBM15yimrJETQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr
    namespace: nde
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeElzRmlBQkhqUytOZkIv
            TytLMTA5aU8xL1c4MVJhRkpnSDNDVlJ6L1NzCkhHZ1BoQXZZS1FyOWtRZjVYb2pi
            anJycVhERzRHZFhqVVlWNEFwN3BEdEEKLS0tIERnY1ZXYTMxdFg3KzROQUFhOHN0
            UmUvUldBUWV1czJ2TUd6ZjZSQlgzR1EK46RL+cXxsEFBzCsmubdh2fP7xm66uana
            LF3jrpMtM3CvMvfodkfGObSPdhtoXiEhUS5I0cmoa1cMUK4YiwvE2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T14:51:17Z"
    mac: ENC[AES256_GCM,data:Jgex4dAt2X7JzTyTBa/RIO0lepsbas/w+AnAJ6o3dLUL2Y9rT+FEzn/AdyTia+T99N+ple3fZob6JsNaslXxqziRw6LuR44QubDsmdjpCZBOeSvnl/WldLMsT7fnlK7WKha1rHRMsLm3WkPA7B3BVujMfYOo1KeHLP5DgiEY7cY=,iv:ix51ZiHXiz2Ya5E4AAkQyRBTvWWymatqBBN9x+HILdY=,tag:XAwNiIrHSSsf2CwNucukvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
