apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZmHmRbnMEqqOVRbNh7xyk6NPy2Em0b/A4Mw/ZP50U3LuCJsbcpdL20ECRThTlhEiPvlD3pY4umM=,iv:33HIgaEt0zKL+0ISCQCakLFbY1BjjReHUOftUBSXuZ8=,tag:YN8YPy87G+/jIIw1mKln+Q==,type:str]
    username: ENC[AES256_GCM,data:piyXzrrrMWxTZsiU,iv:ChDTWTrMJPyCHCaU2A3sZpjwPiX3jGtsUjXUCOMzWzI=,tag:QU5UgvOekmCkVL+FMELMig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-nde-bot
    namespace: nde
type: basic-auth
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWWRDTDJnb0N6eFA3aFQ5
            Y2tiTkVnTnExWnlaazFMd0FNR3c3NVN6NURRCk96QVNkdUpmUkxwZ1pWNlk3Y0V0
            QWRDU3M2aTFPQXUrem5iWisrL1QwWkUKLS0tIGpGbzg3RFIySm9CKzl1cTdaQ2Vw
            d2VCL3dEd01wemNLSHgzUmJJTGl4aDgKFfVuCBJFwVq5UiY5Q5gLlYHn5TrSGw8p
            y2HPuLHtmoEsrsG7lH9rUMCixlmVzWL7QqD/JsjixzWZabl3FCJ18g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T09:35:24Z"
    mac: ENC[AES256_GCM,data:C+H3XpcgquJbzAX0hsyWALqHADYnf553fyVXBbaRf4IzSmnE2jhTQFrndr1lrorRgWq8OLC2HtFDoD+CUTKlrQyrPiQVIqrfIR4oz6txWrWJ1AAhVy2fnS55atX3/IfVV+oDxVzhcAKs+HfRsWR17IVBD2Lp6SkPcOUlHe9JPlA=,iv:kgg2uEFnVWvQt7ep5erRF6Frwuyn0Jr2kmMZEIwqQ3U=,tag:rpTUslvQahL7jYT3Kp3+JQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
