apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ynft77TPqdd8+frIxNjYpoU4LsE=,iv:ep/4ZwMYcGxo+2tJWxscixRznZDvOVh4JlM9U1LpVMk=,tag:orYu1TLGZbtZYTkWiEp9EQ==,type:str]
    username: ENC[AES256_GCM,data:fa8hyQ==,iv:VbAlY3sNBTegwDyImwrqDWRDa3tPUEYv70Sa12dgKoA=,tag:OI5GudVIW9rIfcKwIN7XKQ==,type:str]
kind: Secret
metadata:
    name: graphdb
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadWRqcmNoL294VGdxWjdD
            UUhtejMzdWZyUnJFKytHa2xqbElySVdkcUd3CkRSWFJ6VUhFbmxZL0NLbnlkSFhY
            OGdjOGZjWnhueUZUUGZJdjhCbTZua2sKLS0tIDgrUjFMcGhoVVV4QXhGUFdZNG9P
            TEgyOU5RVit4MDNmcE1sQmc1djJ2TzQKe6PhRAVBpEolx0INSfLblkcmD1nPl4IZ
            rUiqtjd3ARoCy472Xe1lQ2fvKd1kwhuINIFxTWGNJg8HAwr8dcG6Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T13:32:11Z"
    mac: ENC[AES256_GCM,data:wnH0Qh7Tz1JmlQ7x2uQ4VFIh+4G+ACf77MlJI9V5m5qgu1QEHalONWFScy3jBOysUDsXuQWUI6ryFLRe99uO6JHRaKRZktFRNoTkIwsUFiNb84yz4ZfZraY++7ahC+fgApXlKfozdRLT5ceGfs5f2jT3ABZL/pA7VhmwRJ3o+NM=,iv:7ghwHNFcXFHfw4FD95kEZzYTvuCX2jMqWKv4773jWhw=,tag:uADzSXg5wKW6AkGmGbOO8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
