apiVersion: v1
data:
    authorization: ENC[AES256_GCM,data:Zsr7fSpv4rrslPDq7O0HTFpW0rVfLJZ/j4Y1bxjaVHY3eTIKGzTCVlepw4JeFyho,iv:TAs01zqYIOyyzcO9pm/30V3ShHgPfLDaPDOnbXJqau4=,tag:uaOT+X4GrmLzOJaHvCF5Xg==,type:str]
    password: ENC[AES256_GCM,data:ntsKwyem6qth8hnZzI0cXlMOUDM=,iv:uhbl/f6UMQ3/bCDME30qpiTCRT3cxUTaBVPx0Qe+Zes=,tag:lfdMABg0+pyuZ16COqmJsQ==,type:str]
    username: ENC[AES256_GCM,data:eNjGCQ==,iv:gcpx4DwWOFpcPUzxGOApJrIq5GQ84vuOZBZU2rtNBvY=,tag:JvXGf88RCdQs793JOIIcXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: graphdb
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bkE5RmpmSUxvSUVqQlJY
            dW1ENU5vVmk4eGFVR1dHNnZmSFNUTXRGWG1nCmxhWDVyRjJQWERkNENXbXBqY2pa
            RFV3dm9sWiswNTQ2UU9xLzRQdEluUWcKLS0tIG1SOHZPL0t2dmJkVGMyVFZxSTNO
            SkJpUlcyWlZWWHRZdHhnaS9qZ0MrclUKhQ42Xz/l9R3+gsF/YsvPLjoWVS4PkWpH
            8hlL/CFgmmI3sn3KQyLkPQhexVyUf/hvHQwWQjAabK67e3QTVljsuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T10:31:31Z"
    mac: ENC[AES256_GCM,data:qf3PKA4diHQ7lC/htWJPvkoNXJwDTTf92VPqpGMXEZZK1j14Cs5EsZmnLTFkqY6FswlrdjmknxgRcsrEX6bee9011OUG90OrZvTly4IINl7w3Ga2wQwloIz6uU9wyeyR309H93KTw4ZZ0bCAi1k1FXKweduDANnqEiF4mN99bog=,iv:sqQ/+9JzGUV7Og9yN5mGfZrt+3sJJAJRlZiVw6OEZ14=,tag:4B37UkRWi/THDmaSiF3g8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
