apiVersion: v1
data:
    admin-jwt-secret: ENC[AES256_GCM,data:aEccmnCP2mcls062RIt+aw1buXLrJxx1qh78Vfzuosc=,iv:5YSIyOhTYydYSmvFkKQYQJ/lYjzpxFAlfhERrVMzDEo=,tag:u+qLPyfcQI/Wr66r6h7VzQ==,type:str]
    api-token-salt: ENC[AES256_GCM,data:uaEj9ORFFlrxcKLDScgQa5divVM8iVY3VF5gLw1nsOc=,iv:8bJUmOoK9idvTqfQdZN7NPHzVvWBr0c7YISR5KHn2qo=,tag:0saP7aJC03xUJEepkkvnzQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:JqxNTwSkgQz9hkWxxgw9AkZYD4qZcW/UYaqFNUqhnKU=,iv:3/0SAyP8NwvogKn+GbJ4AfwM7gSgqxfGAFfG++QIYFw=,tag:3hXp/TLb1Y47Sp0TA//ZKA==,type:str]
    keys: ENC[AES256_GCM,data:RYfkPVJrtYeNzjCLd1HMIphxBz1mcSxxr/u3dxsVd3KDAEw20fku5Xhp+ZdE3+6/WqSr3ODv4RhweSI2TUmGhYuZ35cWdInEpml/QKh30m9Kx+JUdyjUUpQ9//g1eq2XtVO5JyWtcyVqQ1A03Xhn0o1BtFErObOg,iv:TVof1ZsQB4715fzKwzs3ovcIaOXxPbNNrLft+SjSZ5Q=,tag:GRdHbTnT+DPP2U0t5ecmpg==,type:str]
    transfer-token-salt: ENC[AES256_GCM,data:ocBiXYX5k8/d+E7YNglisZwQ5Tr91WSjZwbQ4ON3no4=,iv:CP/qZuDYooYHyuo2iJhot84IbLzNITp/BPKRGv45vuc=,tag:QBXWDI9Q977U4uZdwRBoqg==,type:str]
kind: Secret
metadata:
    name: makemyflix-strapi
    namespace: nde
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVG9hT0d1K3Y5NlNTOXI3
            UmtPSDJOT2ZpVmJoTWdZRE5YUW0wVitVd3pFCnliRFlWdWM5VnF4QmJGcFBtVmh5
            bkVWVUcrb3QvOFV0RDJ6aFlvcHZSTzAKLS0tIGU1Qk1CRCtId3NEWkU5TCtqMnQ3
            UUwyR2ZoRGhYeGFnSUpJek5VQ2ZUM2MKUQMs+8n46Gfsft6lIwyr14QlF3uJgwVU
            R4HImyztxyqiBecyQV1rqMLoe8UQbMxg3Ne7VBu6hUf3fSw5dx1gdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T13:40:29Z"
    mac: ENC[AES256_GCM,data:FOnAGnzj3mqLLNZxniCqOSnYp3J4bPelXfBdeeKluPoKisa8uNJehQaltXWkO/CILfRWk4ZyvXaGDT1feHhF4F0x8Iq6FPcOBBuwX/nTwJwN+1Grh6AvQEqUtHu0RDstRW/LsqcQB1xBJbJVzN+4ddXP3oh9fsvdEV0fsxbreXI=,iv:tYAwx0P5ENWFizwNYoTlVu0flp0gWn9JdaThl7QXQVs=,tag:hWYeggEFPUu2L69ovB8SHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
