apiVersion: v1
data:
    key: ENC[AES256_GCM,data:sskHbWazJ1kGhTM8t6CTBv7LXwwG+8e0stoJeA==,iv:WFHAuDOv2kUCl24lnbB9k1SDb5qTI7VxsecsSxcdfQE=,tag:ldP7m78s/QIFJCLeG6gSVA==,type:str]
    secret: ENC[AES256_GCM,data:TINlLdHQl4LRdLfnMWHNF+3ygNWEhL/CzJldtxhwzlc9EeYUR/NS0JrD7uIQPYfMF1ePAh+9Sfb+OBqL,iv:J6B7Zpu39GL6+pwHHEE5X4qHAXmSK8mQGBQZ6gdFVfo=,tag:QeHM1xmNyvVO1Q2THkSMIg==,type:str]
kind: Secret
metadata:
    name: makemyflix-strapi-s3
    namespace: nde
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUdGRHBYZm5IR3NaTGJ5
            WXhJRlJ5OHV5WHI5eFN4eW9CU1NMYU4ybzJRClYwSlBISHVoS2lId0F2V0YvMWpx
            bFdUenVDRUpEQW5SOXdwalBuQ2RqTkUKLS0tIGVqdGtmaUczZ3FOUjFUZE0xZ2Y1
            SmtRc09ONXY3YktreEtrTU1LNTNiTXcKdD+qIDWSmtTwbWL0+YMSt5xaS0w3QTQw
            eoDfhtySVJFmr2Jx7mT32h+1lBbAqpDKsiVKF7R21tdpAW+PHzvGuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T13:40:29Z"
    mac: ENC[AES256_GCM,data:zc2OqUWJ92nXvhm7s3wVfY9NO0AKjEhJE2ybFTsH6vECVODHg6udiv60RRY2g1b3vV8SJTrN7uJt4M4y2PJjUf92C895UxLn5rMlBXj8CICc/8aO5VrKoEiQyoa98RVPiftV4/juRYTH2FfQWaQJwvfbjRhJS5Y8BV/cp3R2ZcE=,iv:mpEwXrTKKEbr4hdSByXJLzKmUQqn2wE9fWijRMLhaoM=,tag:HT9D9r9sQJVd0YPeLEEMuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
