apiVersion: v1
data:
    password: ENC[AES256_GCM,data:n8DaFvUGMhVw8CnSiUpDH/3Gvs8Ytn88+hZ2JA==,iv:Ko5/G97qlKwacv74xwZ2xRes3Aqd91IN2mS4VFkFQzI=,tag:hGBtA8e+jQujQRJ55qOXXQ==,type:str]
kind: Secret
metadata:
    name: makemyflix-postgres
    namespace: nde
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVkg4K3BiOTU3Y05wNGlJ
            b2xiVWlyZkdZYWFDRkVnbTFXeEZvcUI5UVYwCk8rZHNUWEJmQlVxNU5KVHNsdUNL
            M2p4QjZDc1NvTUlrMWFKMjhFQlF6ajQKLS0tIGpSWE1iVjNBSXVPWVdBb2I2REMx
            ejNmaWt3YmpyVC9hTng4Y0tnZFhWK3cKDhaB2Ql4YL8nJ1YNrIYpaCU7j8MDzQmT
            8YZYJo8mIVUJ1ZejW9AjbO0k634DuUCYTgUlUPXIhHT0Co4k6sta8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T13:40:29Z"
    mac: ENC[AES256_GCM,data:+f2Dy/+SvXfkHw2gvN3OngVmoqc1aN35DxfDxZDQmGTFnZ73qaATm2zTwuleKG6BcYnTd0Yz3Lc73YA8nh/WPIU36yTI8QHDnvI8K26Z82fceZx2/jr/5AIhbRFO6nWz/TZMpjuXDgll0KMkNBqQx50NczFh+VwX2tTBx7iFPd8=,iv:Be0GrMOnS1d8ZnKdYdzYqy115c30LFZ+2tgv2P+FPVs=,tag:FrNWTWjzOG6v6kl6dIJq/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
