apiVersion: v1
data:
    token: ENC[AES256_GCM,data:POpGN3d29NAmfMDZ9tj/fBuQJJuQQ6Ktb6Yzvryt6hH8nu6eqz4X89+uPD67YN4c6GjZ7LyHJyuZzBvvIw8K+KU2sE7U3PPYddQmUwFfLPp+AE/Oll1bIuRzTFsDd176nmPnBYqrCIaXoymaZaT5z3Xoa6Umpw2wwOWfeOMueDpYfKqmjHtRVC80ItsRH+WYzyXetkM/xmjjLDTsCc9e5mRnzElNkHV6djeLslNOAbM7TWB4nGa9oGxL6Hh89ouaZ6Oyi+TffDY/NIKJGGQ5QLgd/QXnOh4PFDBz94t9fnEFDx+WcTGY02MWyseBWMAXzuZHBjplFBZCkMHsrTq+f6Mmgix0n1WJdV71dWb6bIJUt14EE7pb9ixXR6fEySY73CqVei+61+onBIcYqdhrm9ZDAcOZwIutjkZPgUv0SQMdqedG2QqWuj/S6iirNDcX84FKsHk4SV4=,iv:tUOWLvTkVDn1qwdexZfUAiqGL7xQXl7Yl/k2awRqLjk=,tag:NbA+Fuld0ey9ar9IBXnKKQ==,type:str]
kind: Secret
metadata:
    name: makemyflix-nuxt
    namespace: nde
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdTM5ZlBIUWlkWW9ONmJ3
            VVE3emQ2WmFnVnQxcTYvY2FvRmJFREFyUkVvClV2K2hzcDdNdy9JeUhSdDY1dFJZ
            VCtURVV3YzZFaitsN3loK3BGWXM5QlkKLS0tIFZtUWFGeFQ2NldtT1FoampKbHY2
            KzBsV3Z3L2RndUloYUowTy9kLzRzRE0KPBEZCibpXEpsBp7yT4Y48mxxfBIBj0/F
            k4QOzauubzKZFdw9TYvoPNKb5KuPmImcKHd38Rek0htMS7xBqYsI8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T13:40:28Z"
    mac: ENC[AES256_GCM,data:7lNka/sIe4jCy+Minv9Z7c/pD4kLJElZHJLqbRKGgf5Y8IhnlNLimmHLLDORT4x1hbqHLZ5E6V+Z4Rr0EXqhupcrw1YEzgv8wk9IOUeTEtCkcdqC06nr+Z66bPFtylPBcxlDgbVa/qXvKJnQ9XtdDWHSBW+Icxf3UoQAG8Z7pJ0=,iv:++/9ZQkGzAJJzVsTHJNDJddReXx0zu8okXwUKKawy50=,tag:Fms2hA+de37gagzKYr4Ksg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
