apiVersion: v1
kind: Secret
metadata:
    name: mattermost-smtp
    namespace: nde
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:qOpOZCieY+BGu4vvRlSg0iFfX6gbgeOMK5KjtOuPMCJa31o=,iv:GKthYrh+Oy2E9FA+ontB5RCIpe64fO5TSPmoczg7zRk=,tag:xSWsZ431G69fEBg59Gk9ww==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST2laR3dlNjNHZlkwcnQ1
            eUxTaEdWQ2h3ZWU0N0ZhV1N6cXlFcEV5VGprCmlnZFVMQzc5cDhsRExMa2dnZU9Z
            cjFwUmZ2d2RKYkRvMUpDdlM5bVpzenMKLS0tIHZuOVFPT21JWU1xL0F4TTg1d0ky
            WTNUWVU2emdGK2h5MmpLZWloNDc4YVEKIoI1ZFaE2F6I3ILOPhhw1ht2YQCsi5/N
            9eolwrcvpet8/v58M7VMgQk8H1hmBIizncrxYWaEyDQ1BrKiSyIbMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T08:53:02Z"
    mac: ENC[AES256_GCM,data:bJ9kr2ToeyXR5sRF3zlyt5BK6IAEf50Jwc97BtThagKA2ezIVnJfv76PeJ/wkH77StbB00XIm5GR4dBTXHtq4GVeMXWz+kDVb796H4h2BrPPtuUKWxapxtb08Hf3FcJZPgJGIuTzb9SX+j6WDjT3NmLVSzfLgJqf6IagharHnr8=,iv:bWVDxaliPllnLM8SiP/nctAbdEDwdDvMzFf759SO7X8=,tag:2JH7/IcS6CYKSD0cyc77Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
