apiVersion: v1
kind: Secret
metadata:
    name: mattermost-postgres
    namespace: nde
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:vOGnniG8VqxCXeFnX6fQxvLSoxiRcuCDZRTm17rCsDY=,iv:AA6lwXxOQ3jzTBpPYRmpTLTP7PPA20H0g1EfxOsfv2A=,tag:UOlbEQoTbV2TVAegz54Nzg==,type:str]
    datasource: ENC[AES256_GCM,data:K1YNdso6cF3E9gn6HsChhKYAmW+c332eexlw2DfmQ1JZZaNmvoi9wr4l0BbDtUfWMJ5oT+Fvra69Q2zMMAOM0wqTfGL5IAcgIbfpumPQKK0z/tiDTFjuDG3SN3h+LShfTQNTC5CtrTYAjGKsIXYHAcv8jTK6EFMZaANH3H0=,iv:6CKGbWkp38IMWPbYBMjwXenwEgv5zvIi8zyK4PCXFag=,tag:K6nqaGN9vZ7xhrx3bwQEAw==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1c0QmNCQU82OHFGTGlH
            TnFMMVdsc29VWkxGTzVmaFAzK2hTdzhFRDNvClhJZkhmZDdBcWI4YUtDanZLeUVi
            MmpDcEM3OVhNWlVoRTcrOGl4ZVJXcGcKLS0tIGZBTkQxZkpsVnRIRkwwMjdQT0hi
            M21seUJDbVVsWnhrRGVqemlGS2F3MEEK1TVFLKRevyUY1cmaf0TMbvp7P3nbSMh4
            fkNlM08JDC0e2AjNsn229zpERWx6b/SgmN7Cn7O2ri6OrmUajjKPNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T09:04:32Z"
    mac: ENC[AES256_GCM,data:/QBhuN46j2RJ6qgtVWQnpBoz6h71M7u7VJpMeXvvsKz5KMbqTTHzMP7XpP6aoCuxAVJKBuDy0L35DT124NffkRFlgA5A7xSLUFeEgfFbbQ/BPfwoAmn9bkKlfq9Eo1tk/tSJX/3BTBfUzMLXRMFFOjGweY6f3iUiv9i/TbYXS0I=,iv:RlcId3MDNyJ03lRp79Sj/jgbIO1c4AKKWG9leDqPs+A=,tag:1lTvE55O/9Ig9bfB9q+3Bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
