apiVersion: v1
kind: Secret
metadata:
    name: network-of-terms-gtaa-credentials
    namespace: nde
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:LiVzivxMjN5dGyW+QQeQVTUVhvofd8rrueIi7EUG,iv:l1taEZUzIUcbydxvvX6dcDx/XEk+pSgGNwtQ+8zUMoo=,tag:Bs8ru2AeS1VWQAbTmYFe6Q==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3ZyQk5pWTFqaUxaSTQr
            cVNxYk9hbFRUR0YzYUJDeTQ0b25LM1g5bm53CmFuWmErblNFNko1VjBwYkRWMkUr
            N1EveXF4UHlTbHBWa3FpMjZaL1B5ZVUKLS0tIDlVbTIyQmdZRTRzWFVDZmV0dUh3
            TWpvZ1RaQlV4VWtBT3ZCMDFXTnBiYXMK1rwGHCNMtOSSlf+CXPd7Yi47oQftq9Mc
            GpZareQ8RD7PkWhSTzFFs3BaWemtwqhiOW2RRywHm9UshNugjueQZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T12:34:53Z"
    mac: ENC[AES256_GCM,data:F97GLmPNZQq3I4zHn6Pa6BbzK/irfqVA6CbNbjrOJlKx+a+FMWDucLNjRz0eLKuxBVbKKe8YCctXmUlRke4ICsH77PEgzyBayHvH0zKBiK42km8UwDzqSmOMpBLLw9PELcIi2pYto0DyeeiX9iwglJOo/IeAt5qt2aTQDDcKT7w=,iv:WhJIYczBUUcl7rUdv6moN7wlbsfpbTc4SMm9Fu7vWzA=,tag:CTOwGT9RY7+oiTDNjprE/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
