apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tCHejHc/J/YdwzhtJxuEX+dgmk400Rw7luFy6YkmfSc=,iv:8w/DfVOGNJyg5MvIiesD7rGeWOpk9nz67dalseVW1Z0=,tag:wXsbnofrlrEP+nXydjVkaA==,type:str]
    root-password: ENC[AES256_GCM,data:bd56hLEEmWK5Spby0V0pxGkIYtu28x8vQJsQXKzw6U0=,iv:u0FTQbD0ILwefSX8M622+JTI8seG8w7EoAhCJ+iAuSw=,tag:vXrEV96xsI/LXR4wxnkWFA==,type:str]
    username: ENC[AES256_GCM,data:2uQsGbz6F2Q=,iv:dMxTOM6kLJYxh3T9vU3hED7EV+mNyq7v9ltlbSF4u4g=,tag:rtEAdP4QiPPkXHdcHDcNsw==,type:str]
kind: Secret
metadata:
    name: omeka-mysql
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcUdWV3Y5dEFzM2hnQ1V2
            dXlvTTFoUUhvNzVwSis1ZnQzVi9MbDdNMG5JCml1Tzh3Tmwzb0RiRzgvU2M2Z0hX
            MGd3clIzUEpYeko5WjFob0xkQmxncDgKLS0tIEZXTUdpTzJiYURKTkhZMzdnYUQv
            YnhucG1EWEZQcUhtM0pHYWRTTGJKbmcKWRUNKCvICwI2uwUF4yWVJNniFmKbt4Xn
            Tf18A97eQSmYEKWxtvZQ7YZ+LAulNwjIQLa7hfLUe7WVl6kOBGzWFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T18:44:45Z"
    mac: ENC[AES256_GCM,data:kDtJTfMBGRivlIYssr5UH7a/kF9/yVvHfD64VcNhnf3TzFaMZc+HpOglMDcIGO8tlo5NrVvUL6+OaHU8sGMjGAyzNznRcr4r2A5X/xnwzz/v92DOMQBDLaiTDzzOj94rjMphJDAP+ptTHywY8IVQUHrti9p+QjHdIspL1krL4RE=,iv:SbLQrTjGFevKqqx5Juk2SmRRt010vksmyi9XC7Tiknc=,tag:i8By+8NzWi0TBTbhibR53Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
