apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9Rn3g/ZsdU4AfqDsW9AdwdhTuMOa8gTPtfd/hA==,iv:hnQ7p+PJu/lKSUS9SGeRRRpQ2HO2Wpcu4g+NIRgoFus=,tag:FO3kz4r0COGGSZVO45Wvbg==,type:str]
    root-password: ENC[AES256_GCM,data:5VwpLvkTrNi8AieQ5O6VE83i0OHAMDj7AMpw2A==,iv:nQUkKXNdY8iOzHXWUSBrGtQXn397CyjdpFTN9daZzNk=,tag:pRCHdGW8vLX0KQZQbFmufA==,type:str]
    username: ENC[AES256_GCM,data:j0+f4LFMGiC04NGSXrlj/w==,iv:ozozVFtkvSBLYzs+RrwPqLaT8a3RYAj6T/Jc3Y1IATk=,tag:snO86m963CNwMtkcOeeNpw==,type:str]
kind: Secret
metadata:
    name: omeka-s-faq-mysql
type: Opaque
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQmRERk5FNFFyKzVvV1ln
            UWJZbVJyM1hnNWlhTm9qZEdtNVkvRlJuMWdJCkxCQ0E3cXA3dGRVNCs3Qnc2cldL
            UFJkZU9vTzBRV1FPeWJSZXgxZFQ1eTgKLS0tIEoyWWpMOHlZWnd0ak96eFNhSDFI
            OFVHWFhPT0t2WEp4SHZOcldJbmVGREUKCnPyHFcDo03lGllfKIoQdIZ6OkOMZ5rz
            OCD5amumoIMlm151obGrfUp/YsJkDCtn5Zu/TiIsZcFARt6rpR/RmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T21:31:12Z"
    mac: ENC[AES256_GCM,data:7Vyps/itZxPRCRb4pam2bfyIpeL112ThrfkTBcvmHRt5tWz7jLPxO7hHeh4kvbulRh/1yNida+9DeT+cQb7NHoVLB3wHvEFQ0eGouNePTbNkjsSVOVGHiRajfV+dswYKFgSU2O1Yc2xwFlrQw22TicUszZr74Qmt2Yk/ThM+tlg=,iv:TAWqFJTqTA17wvKXfPCqqz/yei1Hte/hG/JJsytegjI=,tag:krzy2dbWocTCP29wE7omZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
