apiVersion: v1
kind: Secret
metadata:
    name: smtp
    namespace: nde
type: Opaque
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:/H4Bhr3B2BtbEbiYYw4G2LR7,iv:LdLL6A5fAUoyObZYCamcz88Ta8uBWxI5Nr+a/0bkjuo=,tag:IEB/F/pCRMOuI5+YF0sWvQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:zRVmT+qvJz8oYQ==,iv:CKEnhMfj5xesNV+Z7cmYx8zCTtAYtiq+1/X6usOPjCg=,tag:phhD6LqoXpvQ7UvF/GupHQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:Uo5MY7eYQO2lYFKHygkG+RhjmN8xixBeWoJ/JR+nDavS2xg=,iv:Olb6hk+rh9Yh42qlnneQcoL3CBmA/DMLSiy4Xuf6HvY=,tag:yybE83BPsJ0/bNdoaay3eQ==,type:str]
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SkN2NUpJa3hxaTFTUlZP
            Sndsc2dtbEFyVXhxZk00UnlVY0I0VjNpalU4CmhYMEpFL3d2Z0lQMFYyVXdMNFp0
            SlU3dW12VjFuSEQ2VEZ0a3UySVBCK28KLS0tIE9GZ1Bxam56NjNieUY4WFlEVUFE
            ZGYyc1kzTlB3SG1CaEw3U3ROeWpWc2cK54sB4A5kvw8eX8OwNFY/cWR3njzrCvqt
            G1dpJ85Z8VBCrWq6x4X2olN77DOR8PcZ3qXqvFzUQBqXEYBnGJF04w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T09:36:47Z"
    mac: ENC[AES256_GCM,data:EXzkbcfd7V6G7RO9izwInuy82FjsQLdP/gXFWJSTxh4v2gpHp4DWTwnCm/Tdr3xafublhP7uaGallA7oTTtiER2ZtSKdURDYfDsMm8HXccbjPXLbrQI4V2ypmZh5VOVeCQDJPSmIQIR9ARvwx7c/7KrUq41dnm3byJF8aUxIE54=,iv:fq4nCPXclgalp1cjokFXNtMmRzkzOF5465LWM5AnAVw=,tag:L2X1cW32b6tQRivNSwY9lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
