apiVersion: v1
data:
    database-url: ENC[AES256_GCM,data:xiM/3Jkf9XMjiIVrfKg2JHT4vXGw9y2czfQvfShJEAuP0HCcj6OAL7IhSbDXi5/BBcDfGXA5RHe2J7UDCQeJAVJlAx/WbeArTOanXGRnmwsMfIOShVD8wos4K7IVBxFXWP6Hc4+G2v517i1mbAXujw==,iv:XMP6XC4UgUzaLaM1nssah+DfniXsXB7pCUCKPNyGOa0=,tag:jK2XASPm7Yv59VPaEQsaAg==,type:str]
    password: ENC[AES256_GCM,data:h+xJfdDEh3gBCV7oMvjEnk+8qAafRtd9reX5NrjrEBpwFtfj6A3RK7ZzZsc=,iv:Eo51//5MrEhm8TQYJiZn9P6UZcoWleGIQdbB4jk9EgA=,tag:kyx95i60I1QBVLyOvHApOA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: status-postgres
    namespace: nde
sops:
    age:
        - recipient: age1qnjmyern7zmm5wpsclrpexu327xuqalpcthuk32hj8xn5ssts96s5hhhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UUljNjdpUG5XeEdFdnQv
            d3Y1azZXK1VXMFFXbEg1a1VsSTcyaWc5V2pJCnovQ2ZOczJHZ1UwaENtdXUxa1Yx
            SThJZUlrbjVkNTJUTkZTSnp1WEhyeVEKLS0tIFhwVFB5bEhoNUpmbWtIeEhQaDVB
            R1BzM05pME95NGRRbWlRY0Ztcm1LdWMKh7s1/nTYcBH2/l9PNdL+NVRZyA2VJbvJ
            xZZR8BQmi870B6BN2cDI7k/+Et9SkmOmSbzZP0aCQ5LiouMCLt3XhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T19:10:13Z"
    mac: ENC[AES256_GCM,data:HrvEO1AoMsR0MkztyIkBOOdHC062Cu/hLaEVbeEV7BqAh1xogi4TWAHW9vnqvKRrMXu7vovKdbdnuWE7WlYXBBxGINQ49p2kDvCe+k3MUhoWTu0CwAbORNhcsrzEeSXZNeG9tdrZy0jWnNYgmhQoEgu9WC24ZnWTaNeZCNHfhPM=,iv:XOIosbIdvHQTdwB5SpcdTBjgGJWeagBkbRngrlpKVRY=,tag:ZmUvpx3W2N8E6tbo3bF6BQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
