apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dera
spec:
  serviceAccountName: nde
  interval: 30m
  chart:
    spec:
      chart: helm/nde-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: nde
  values:
    externalService:
      enabled: true
      ip: 84.22.101.57
      port: 443
    ingresses:
      - hosts:
          - dera.netwerkdigitaalerfgoed.nl
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
