---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: registry-demo-php
  namespace: nde
spec:
  image: ghcr.io/netwerk-digitaal-erfgoed/registry-demo-php-fpm
  interval: 1m
  secretRef:
    name: ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: registry-demo-nginx
  namespace: nde
spec:
  image: ghcr.io/netwerk-digitaal-erfgoed/registry-demo-nginx
  interval: 1m
  secretRef:
    name: ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: registry-demo-php
  namespace: nde
spec:
  imageRepositoryRef:
    name: registry-demo-php
  filterTags:
    pattern: '^(?P<timestamp>[0-9]{14}).*'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: registry-demo-nginx
  namespace: nde
spec:
  imageRepositoryRef:
    name: registry-demo-nginx
  filterTags:
    pattern: '^(?P<timestamp>[0-9]{14}).*'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
