apiVersion: apps/v1
kind: StatefulSet # https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors/#dobs-pod-owner
metadata:
  name: dataset-register-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataset-register-demo
  serviceName: dataset-register-demo
  template:
    metadata:
      labels:
        app: dataset-register-demo
    spec:
      containers:
        - name: php
          image: ghcr.io/netwerk-digitaal-erfgoed/registry-demo-php-fpm # {"$imagepolicy": "nde:registry-demo-php"}
          volumeMounts:
            - mountPath: "/datasetdescriptions"
              name: data
          ports:
            - containerPort: 9000
        - name: nginx
          image: ghcr.io/netwerk-digitaal-erfgoed/registry-demo-nginx # {"$imagepolicy": "nde:registry-demo-nginx"}
          volumeMounts:
            - mountPath: "/datasetdescriptions"
              name: data
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr
      securityContext:
        fsGroup: 82 # www-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: hdd
