apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-image-automation
spec:
  suspend: false
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nde
  git:
    commit:
      author:
        email: nde-bot@users.noreply.github.com
        name: fluxcdbot
      signingKey:
        secretRef:
          name: github-signing-key
      messageTemplate: |
        Automated image update

        {{ range $resource, $changes := .Changed.Objects -}}
        {{ $resource.Name }}: {{ range $_, $change := $changes }}{{ $change.OldValue }} -> {{ $change.NewValue }}{{ end }}
        {{ end }}
    push:
      branch: master
  update:
    path: ./k8s
