---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: network-of-terms-demo
  namespace: nde
spec:
  image: ghcr.io/netwerk-digitaal-erfgoed/network-of-terms-demo
  interval: 1m
  secretRef:
    name: github-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: network-of-terms-demo
  namespace: nde
spec:
  imageRepositoryRef:
    name: network-of-terms-demo
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: network-of-terms-demo
  namespace: nde
spec:
  suspend: false
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nde
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  update:
    path: ./k8s
