---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: network-of-terms-demo
  namespace: nde
spec:
  image: ghcr.io/netwerk-digitaal-erfgoed/network-of-terms-demo
  interval: 1m
  secretRef:
    name: ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: network-of-terms-demo
  namespace: nde
spec:
  imageRepositoryRef:
    name: network-of-terms-demo
  filterTags:
    pattern: '^(?P<timestamp>[0-9]{14}).*'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
