---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: openrefine
  namespace: nde
spec:
  image: easypi/openrefine
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: openrefine
  namespace: nde
spec:
  imageRepositoryRef:
    name: openrefine
  policy:
    semver:
      range: '>=3.9.3 <4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: openrefine
  namespace: nde
spec:
  suspend: false
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nde
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  update:
    path: ./k8s
