---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: openrefine
  namespace: nde
spec:
  image: easypi/openrefine
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: openrefine
  namespace: nde
spec:
  imageRepositoryRef:
    name: openrefine
  policy:
    semver:
      range: '>=3.9.3 <4.0.0'