apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openrefine
spec:
  interval: 30m
  chart:
    spec:
      chart: helm/nde-app
      sourceRef:
        kind: GitRepository
        name: nde
  values:
    containers:
      - name: app
        image:
          repository: easypi/openrefine
          tag: 3.9.3 # {"$imagepolicy": "nde:openrefine:tag"}
        env:
          - name: REFINE_EXTRA_OPTS
            value: refine.display.new.version.notice=false
        port: 3333
        livenessProbe:
          httpGet: {}
        readinessProbe:
          httpGet: {}
        flux:
          enabled: true
          interval: 24h
          policy:
            type: semver
            range: '>=3.9.3 <4.0.0'

    ingresses:
      - hosts:
          - openrefine.test.netwerkdigitaalerfgoed.nl

    cronjobs:
      - name: clear-projects
        schedule: "0 4 * * 6"
        image: alpine:latest
        imagePullPolicy: Always
        command:
          - bin/sh
          - -c
        args:
          - |
            apk add --no-cache curl jq

            csrf=$(curl -s "$ENDPOINT/command/core/get-csrf-token" | jq -r '.token')
            projects=$(curl -s "$ENDPOINT/command/core/get-all-project-metadata" | jq '.projects | keys[] | tonumber')

            for project in $projects; do
              curl -s --data project="$project" --data csrf_token=$csrf "$ENDPOINT/command/core/delete-project"
            done
        env:
          - name: ENDPOINT
            value: "https://openrefine.netwerkdigitaalerfgoed.nl"
