apiVersion: v1
kind: Service
metadata:
  name: {{ include "nde-app.fullname" . }}
  labels:
    {{- include "nde-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default (index .Values.containers 0).port }}
  selector:
    {{- include "nde-app.selectorLabels" . | nindent 4 }}
