apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-statefulsets
  namespace: nde
subjects:
  - kind: ServiceAccount
    name: statefulset-manager
    namespace: nde
roleRef:
  kind: Role
  name: restart-statefulsets
  apiGroup: rbac.authorization.k8s.io