apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dataset-knowledge-graph
spec:
  serviceAccountName: nde
  interval: 30m
  chart:
    spec:
      chart: helm/nde-app
      sourceRef:
        kind: GitRepository
        name: nde
  values:
    pvcs:
      - name: imports
        size: 500Gi
    cronjobs:
      - name: app
        schedule: "15 3 * * *"
        image: ghcr.io/netwerk-digitaal-erfgoed/dataset-knowledge-graph
        imagePullPolicy: Always
        env:
          - name: QLEVER_ENV
            value: native
          - name: QLEVER_PORT
            value: "7100"
          - name: GRAPHDB_URL
            value: "http://graphdb"
          - name: GRAPHDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: graphdb
                key: username
          - name: GRAPHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graphdb
                key: password
        volumeMounts:
          - mountPath: /app/imports
            name: imports
        volumes:
          - name: imports
            persistentVolumeClaim:
              claimName: dataset-knowledge-graph-imports
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "3"
        securityContext:
          fsGroup: 100
