apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dataset-knowledge-graph
spec:
  serviceAccountName: nde
  interval: 30m
  chart:
    spec:
      chart: helm/nde-app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: nde
  values:
    persistentVolumes:
      - name: imports
        size: 500Gi
        mountPath: /app/imports
    cronjobs:
      - name: app
        schedule: "15 1 * * *"
        image: ghcr.io/netwerk-digitaal-erfgoed/dataset-knowledge-graph
        imagePullPolicy: Always
        env:
          - name: QLEVER_ENV
            value: native
          - name: QLEVER_PORT
            value: "7100"
          - name: GRAPHDB_URL
            value: "http://graphdb"
          - name: GRAPHDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: graphdb
                key: username
          - name: GRAPHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: graphdb
                key: password
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "3"
        securityContext:
          fsGroup: 100
